### ISSUE TITLE
Factions can Negotiate with own Faction

### ISSUE THREAD

**Issue by rwallac** [rwallac/ANLEra#1]
Example: Player is Elves, and has the option to "Negotiate with Elves"

**Comment by sevu** [comment]
It's the only way to get new units from you faction, e.g. elvish fighters for the elves.

**Comment by rwallac** [comment]
Their shamans can't research it in universities? They should be able to...
The idea is that the leader can have a "diplomatic mission" to other factions, and gain the ability to train other faction's troops, for instance elves should be able to do all other factions besides themselves, because their shamans can do that faster, as there are more of them

**Comment by sevu** [comment]
I forgot about that.

**Comment by sevu** [comment]
There are way more units to discover with negotiation than with research. Maybe it would be a feature to allow not everybody to negotiate with everybody else.
E.g humans can't negotiate with undead [and the other way around too]

**Comment by rwallac** [comment]
That would make sense, however, I still need to work out disallowing research based on faction. Once I figure that out, then I can work out inter-factional relationships.

**Comment by Lukc** [comment]
I think this issue can be safely closed.
