### ISSUE TITLE
Terrain code matching

### ISSUE THREAD

**Issue by sevu** [rwallac/ANLEra#22]
As you know Terrain Codes are of the Form *^*
Wo^Ewl would be water lilies on deep water.
But W* wouldn't match it, so mermen cannot build a castle there.
One needs W*^* to match it.
<s>However, If I recall correctly, both *^Ewl and *Ewl match it. </s> [needs verification]
`*^Ewl*` would be even more generic.

I'm not sure if you already knew this and it was just this place.

**Comment by rwallac** [comment]
W*^* would allow them to build on any hex with water as a base. I believe that this would allow them to instantly destroy bridges, or other water fixtures that should be there. I do think that *^Ewl should work, but I wonder if this comes up on any other water decorations, and how many terrain codes will need to be added.

**Comment by sevu** [comment]
I forgot about bridges.
I worded the comment bad, *^Ewl would only match area with water lilies, and I mixed things up.
I wanted to explain that there is an inconsistency in the terrain code system, [it's that * alone is the same as](https://forums.wesnoth.org/viewtopic.php?f=21&t=46186&p=613315#p613366) `*^*`.
For the bridges (and rails) one can write `terrain=W*^*,!,*^B*,*^V*,*^F*,!`
The same effect would have
```
terrain=W*^*
[not]
    terrain=*^B*,*^V*,*^F*
[/not]
