### ISSUE TITLE
AI starts with dwarvish recruits

### ISSUE THREAD

**Issue by sevu** [rwallac/ANLEra#27]
I had a game with whatever is currently on the 1.13 server
Ai5 & AI7 (the ones in the west) recruited only dwarvish units

**Comment by rwallac** [comment]
What faction were they?

**Comment by sevu** [comment]
Actually... we played only with human sides 1 & 2, side 1 had elves, side 2 dwarves. Side 3 & 4 were empty. This may have sth. to do with the fact that only two AI sides had this issue.
I think the AI sides themselves were on default settings.

**Comment by rwallac** [comment]
I mean, do you know if the AI sides were both dwarven factions?

**Comment by sevu** [comment]
Replay is here, the last one in the list: https://replays.wesnoth.org/1.13/20180228/
I didn't start the game, I don't know.
To change settings of AI sides one has to launch wesnoth in debug mode though.

**Comment by sevu** [comment]
Turns out that the AI side choose by default a random faction - is this intended?
As for the replay - there was a bug with the "continue play" button crashing the game - it's fixed in latest master now.

**Comment by rwallac** [comment]
That is not intended, I am trying to find why it is doing that- and only for the orcish sides

**Comment by sevu** [comment]
It happened for the left sides, and probably was coincidence.
I suppose faction_lock=yes in the side definitions would fix this, 1.13 also uses force_lock_settings=yes to disable things like that players could set up to be allied with the AI sides, and as side effect it also disables changing shroud/fog/xp modifier settings.

Best to merge changes from the mainline scenario, and to merge the Terrain Code changes into mainline too. (was there sth. else in ANLEra which should go into the mainline scenario or macros?)

**Comment by rwallac** [comment]
I have added your code from mainline, it seems to work now! Thanks! Is there a reason to change the terrain code in 1.13? I don't see how it is better, as the code in mainline works for what it is for, unless my code is somehow faster
