### ISSUE TITLE
AI units destroy their own keeps

### ISSUE THREAD

**Issue by sevu** [rwallac/ANLEra#28]
AI units destroy as well their own castle when they move onto the hex. That does not happen in mainline.
This results in Orcish leaders destroying their keep.

**Comment by rwallac** [comment]
What Wesnoth version was this?
Were you using mainline's version of the ANLEra scenario?
Can I have a replay?

**Comment by sevu** [comment]
1.13, same replay as linked in the other issue, with the add-ons ANL scenario.

**Comment by sevu** [comment]
The movement restrictions for the AI leaders aren't applied correctly (correct way is used in mainline), changing that would mitigate the problem to an extent that it only occurs while fighting close to the enemies keep.

**Comment by rwallac** [comment]
Thank you for your help! I think it is fixed now in 1.5.2
