### ISSUE TITLE
Building University on mine and on University

### ISSUE THREAD

**Issue by vgaming** [rwallac/ANLEra#42]
1. It's possible to build a University on a "mine". This seems to be a bit controversal. Maybe better forbid this kind of "advancement"? Income bonus is lost if mine is converted to University.

2. it's possible to order building a University on a tile that already has a University. For UI and understandability, it could be nice to disallow that.

**Comment by sevu** [comment]
Thanks, fixed tonight. Or already by before by Lukc.

**Comment by vgaming** [comment]
Thanks, clear. Closing then.
